## Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 六便士/㎡
subtitle: zauruso
description:  Girl是世界上最好的语言
author: zauruso
language: zh-Hans

timezone: Asia/Shanghai

# emoji 支持，教程见本文 6.3 节
githubEmojis:
  enable: true
  idName: github-emoji
  unicode: false
  styles:
  localEmojis:


## 修改归档页面、某一分类页面、某一标签页面的显示篇数
## 参考：http://theme-next.iissnan.com/faqs.html#setting-page-size
archive_generator:
  per_page: 0
  yearly: true
  monthly: false
  daily: false
category_generator:
  per_page: 0
tag_generator:
  per_page: 0

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zauruso.com
root: /
#permalink: year/:month/:day/:title/
permalink_defaults:
permalink: posts/:abbrlink.html  # “posts/”
  # abbrlink config
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32 
  rep: dec    # 进制：dec(default) and hex

#permalink: :title/
#permalink: posts/:title.html

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight: 
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: categorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: Aath
#theme: landscape
#theme: mode
#theme: yilia
theme: next
#theme: pure
#theme: maupassant
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: 
  repo:
    github: https://github.com/Zauruso/Zauruso.github.io.git,master
    coding: https://git.coding.net/zauruso/zauruso.coding.me.git,master
- type: baidu_url_submitter





# hexo-neat
neat_enable: true
neat_html:
  enable: true
  exclude:  
neat_css:
  enable: true
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'



jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: true
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: false

      

#search:
 # path: search.xml
 # field: post
  #format: html
  #limit: 10000
Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
    - plugin:
        name: markdown-it-mark
        enable: true

baidu_url_submit:
  count: 5 ## 比如3，代表提交最新的三个链接
  host: https://www.zauruso.coding.me ## 在百度站长平台中注册的域名
  token: 6Cl0iHoqqg35FZNx ## 请注意这是您的秘钥， 请不要发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里


#translate_title:
  #translate_way: baidu   #google | baidu | youdao
  #youdao_api_key: XXX
  #youdao_keyfrom: XXX
  #is_need_proxy: false    #true | false
  #proxy_url: http://localhost:4000

restful:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
    site: true        # hexo.config mix theme.config
    posts_size: 10    # 文章列表分页，0 表示不分页
    posts_props:      # 文章列表项的需要生成的属性
      title: false
      slug: true
      date: true
      updated: true
      comments: true
      path: true
      excerpt: false
      cover: true     # 封面图，取文章第一张图片
      content: false
      categories: true
      tags: true 
      keywords: false
    categories: true  # 分类数据
    tags: true        # 标签数据
    post: true        # 文章数据
    pages: false      # 额外的 Hexo 页面数据, 如 About

nofollow:
    enable: true
    exclude: # 例外的链接，可将友情链接放置此处

use_font_lato: false


service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true

  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.bootcss.com
  

server:
  port: 4050
  compress: true
  header: true